export const MUSCLE_ICONS = {
  CHEST: "/assets/muscles/chest.png",
  LATS: "/assets/muscles/lats.png",
  MIDDLE_BACK: "/assets/muscles/middle-back.png",
  LOWER_BACK: "/assets/muscles/lower-back.png",
  TRAPS: "/assets/muscles/traps.png",
  SHOULDERS: "/assets/muscles/shoulder.png",
  BICEPS: "/assets/muscles/biceps.png",
  TRICEPS: "/assets/muscles/triceps.png",
  FOREARMS: "/assets/muscles/forearm.png",
  ABDOMINALS: "/assets/muscles/abdominal.png",
  NECK: "/assets/muscles/neck.png",
  QUADRICEPS: "/assets/muscles/quadriceps.png",
  HAMSTRINGS: "/assets/muscles/hamstring.png",
  GLUTES: "/assets/muscles/glute.png",
  ABDUCTORS: "/assets/muscles/abductor.png",
  ADDUCTORS: "/assets/muscles/adductor.png",
  CALVES: "/assets/muscles/calve.png",
};
